spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ff_dev
    username: ff_dev_user
    password: fede
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true